#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'reverseArray' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY a as parameter.
#

def reverseArray(arr):
    return arr[::-1]    # Reverse the array using slicing

# Input: number of elements in the array
n = int(input())

# Input: the array elements
arr = list(map(int, input().split()))

# Call the function to reverse the array
reversed_arr = reverseArray(arr)

# Print the reversed array as space-separated integers
print(*reversed_arr)
